### ISSUE TITLE
Invalid state pattern

### ISSUE THREAD

**Issue by pickfire** [otaviopace/design-patterns#6]
https://github.com/otaviopace/design-patterns/blob/master/behavioral/state/rust/src/lib.rs

That is the first time I saw that state pattern which I think is an exact copy from another language (not rusty), I remembered I saw some article that explain state pattern in rust very well but I forgot the link, I remember it is something like this.

```rust
struct ClosedLetter(String);

struct OpenedLetter(String);

impl ClosedLetter {
    fn open(self) -> OpenedLetter {
        OpenedLetter(self.0)
    }
}

impl OpenedLetter {
    fn read(&self) -> &str {
        &self.0
    }
}

fn main() {
    let letter = ClosedLetter("hello world".to_string());

    // invalid (letter is still closed)
    // let text = letter.read();

    // open letter
    let letter = letter.open();

    // read letter
    let text = letter.read();
    println!("{}", text);
}
```

State are tracked using type but not kept as a variable, if kept as an variable it makes things complicated when there are a lot of transitions between states.

**Comment by evaporei** [comment]
Hey @pickfire sorry for the ultra late response!
So, I've seen a code like this before, you're probably referencing [this](https://doc.rust-lang.org/book/ch17-03-oo-design-patterns.html).

**Comment by pickfire** [comment]
Weird, I never seen that part. Still, one could use `State` without `Option<Box<State>>`, at least I think it could be simpler that way, I think I will just close this since rust book have it.
